#!/usr/bin/env bash
"""The Internet Control Message Protocol (ICMP) is a protocol"""
if [ "$#" -ne 1 ] 
    then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi;
